In [1]:
import pandas as pd
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
training = pd.read_csv('Training17f.csv')
testing = pd.read_csv('Testing17f.csv')

In [4]:
training.head(5)

,ID,score_tag,agreement,subjectivity,confidence,irony,happy,angry,bored,fear,sad,excited,spam,news,feedback,marketing,Class
0,1,P,DISAGREEMENT,SUBJECTIVE,86,NONIRONIC,0.220927,0.200280,0.050861,0.127192,0.137101,0.169851,0.061,0.706,0.038,0.179,1
1,2,P,DISAGREEMENT,SUBJECTIVE,76,IRONIC,0.089606,0.186209,0.076196,0.269986,0.275841,0.102161,0.115,0.324,0.408,0.068,0
2,3,P,DISAGREEMENT,SUBJECTIVE,86,NONIRONIC,0.056084,0.337662,0.123161,0.188343,0.228422,0.066328,0.056,0.376,0.183,0.083,1
3,4,N,DISAGREEMENT,OBJECTIVE,84,NONIRONIC,0.044480,0.249139,0.084331,0.223565,0.327372,0.071112,0.064,0.634,0.193,0.023,1
4,5,N,AGREEMENT,OBJECTIVE,100,NONIRONIC,0.045455,0.295510,0.035179,0.237420,0.306869,0.080184,0.018,0.864,0.079,0.010,1

In [5]:
testing.head(5)

,ID,score_tag,agreement,subjectivity,confidence,irony,happy,angry,bored,fear,sad,excited,spam,news,feedback,marketing,Class
0,1,N,DISAGREEMENT,SUBJECTIVE,86,NONIRONIC,0.141304,0.263039,0.030370,0.162778,0.102869,0.299641,0.018,0.615,0.034,0.330,?
1,2,NEU,DISAGREEMENT,SUBJECTIVE,83,NONIRONIC,0.160947,0.264761,0.035402,0.144925,0.094709,0.299255,0.063,0.786,0.085,0.040,?
2,3,P,DISAGREEMENT,OBJECTIVE,86,NONIRONIC,0.170362,0.236801,0.094162,0.191645,0.151905,0.155126,0.031,0.786,0.075,0.074,?
3,4,P,AGREEMENT,SUBJECTIVE,92,NONIRONIC,0.345439,0.123362,0.046313,0.099311,0.069136,0.316438,0.022,0.666,0.112,0.195,?
4,5,N,DISAGREEMENT,SUBJECTIVE,86,NONIRONIC,0.069721,0.170406,0.014859,0.124758,0.550456,0.069800,0.034,0.773,0.156,0.005,?

In [17]:
feature_cols = ['confidence', 'happy', 'angry', 'bored', 'fear', 'sad','excited', 'spam', 'news', 'feedback', 'marketing']

In [18]:
feature_cols

['confidence',
 'happy',
 'angry',
 'bored',
 'fear',
 'sad',
 'excited',
 'spam',
 'news',
 'feedback',
 'marketing']

In [19]:
x_training = training[feature_cols]

In [20]:
x_training

,confidence,happy,angry,bored,fear,sad,excited,spam,news,feedback,marketing
0,86,0.220927,0.200280,0.050861,0.127192,0.137101,0.169851,0.061,0.706,0.038,0.179
1,76,0.089606,0.186209,0.076196,0.269986,0.275841,0.102161,0.115,0.324,0.408,0.068
2,86,0.056084,0.337662,0.123161,0.188343,0.228422,0.066328,0.056,0.376,0.183,0.083
3,84,0.044480,0.249139,0.084331,0.223565,0.327372,0.071112,0.064,0.634,0.193,0.023
4,100,0.045455,0.295510,0.035179,0.237420,0.306869,0.080184,0.018,0.864,0.079,0.010
...,...,...,...,...,...,...,...,...,...,...,...
495,86,0.371046,0.090120,0.038222,0.157332,0.096035,0.247245,0.134,0.262,0.254,0.345
496,86,0.203001,0.180778,0.056671,0.219553,0.148039,0.191958,0.036,0.651,0.068,0.211
497,84,0.099704,0.071673,0.021989,0.258639,0.449670,0.098325,0.403,0.219,0.231,0.090
498,86,0.023222,0.498391,0.069340,0.170248,0.191952,0.046847,0.024,0.196,0.057,0.011
499,86,0.224608,0.197642,0.048532,0.158024,0.083060,0.288133,0.040,0.851,0.051,0.054

In [21]:
y_training = training.Class

In [22]:
y_training

0      1
1      0
2      1
3      1
4      1
      ..
495    0
496    1
497    0
498    1
499    1
Name: Class, Length: 500, dtype: int64

In [27]:
x_testing = testing[feature_cols]
x_testing

,confidence,happy,angry,bored,fear,sad,excited,spam,news,feedback,marketing
0,86,0.141304,0.263039,0.030370,0.162778,0.102869,0.299641,0.018,0.615,0.034,0.330
1,83,0.160947,0.264761,0.035402,0.144925,0.094709,0.299255,0.063,0.786,0.085,0.040
2,86,0.170362,0.236801,0.094162,0.191645,0.151905,0.155126,0.031,0.786,0.075,0.074
3,92,0.345439,0.123362,0.046313,0.099311,0.069136,0.316438,0.022,0.666,0.112,0.195
4,86,0.069721,0.170406,0.014859,0.124758,0.550456,0.069800,0.034,0.773,0.156,0.005
...,...,...,...,...,...,...,...,...,...,...,...
145,83,0.269992,0.125215,0.000000,0.195419,0.160119,0.249255,0.156,0.448,0.251,0.121
146,86,0.249565,0.163183,0.108720,0.126531,0.019208,0.332792,0.047,0.246,0.129,0.570
147,86,0.144463,0.281143,0.025940,0.096741,0.079203,0.372510,0.062,0.704,0.080,0.135
148,74,0.129132,0.276883,0.083767,0.167773,0.182157,0.160287,0.082,0.502,0.246,0.102
149,86,0.074678,0.324675,0.201479,0.149183,0.106143,0.143841,0.145,0.283,0.322,0.066

In [26]:
logreg = LogisticRegression(max_iter = 1000)
logreg.fit(x_training, y_training)

LogisticRegression(max_iter=1000)

In [28]:
y_pred = logreg.predict(x_testing)

In [29]:
y_pred

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0])

In [30]:
type(y_pred)

numpy.ndarray

In [32]:
type(x_testing)

pandas.core.frame.DataFrame

In [33]:
x_testing

,confidence,happy,angry,bored,fear,sad,excited,spam,news,feedback,marketing
0,86,0.141304,0.263039,0.030370,0.162778,0.102869,0.299641,0.018,0.615,0.034,0.330
1,83,0.160947,0.264761,0.035402,0.144925,0.094709,0.299255,0.063,0.786,0.085,0.040
2,86,0.170362,0.236801,0.094162,0.191645,0.151905,0.155126,0.031,0.786,0.075,0.074
3,92,0.345439,0.123362,0.046313,0.099311,0.069136,0.316438,0.022,0.666,0.112,0.195
4,86,0.069721,0.170406,0.014859,0.124758,0.550456,0.069800,0.034,0.773,0.156,0.005
...,...,...,...,...,...,...,...,...,...,...,...
145,83,0.269992,0.125215,0.000000,0.195419,0.160119,0.249255,0.156,0.448,0.251,0.121
146,86,0.249565,0.163183,0.108720,0.126531,0.019208,0.332792,0.047,0.246,0.129,0.570
147,86,0.144463,0.281143,0.025940,0.096741,0.079203,0.372510,0.062,0.704,0.080,0.135
148,74,0.129132,0.276883,0.083767,0.167773,0.182157,0.160287,0.082,0.502,0.246,0.102
149,86,0.074678,0.324675,0.201479,0.149183,0.106143,0.143841,0.145,0.283,0.322,0.066

In [42]:
y_pred

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0])

In [46]:
x_testing = x_testing.append(dict(zip(x_testing.columns, y_pred)), ignore_index=True)

In [47]:
x_testing

,confidence,happy,angry,bored,fear,sad,excited,spam,news,feedback,marketing,Class
0,86,0.141304,0.263039,0.030370,0.162778,0.102869,0.299641,0.018,0.615,0.034,0.330,0
1,83,0.160947,0.264761,0.035402,0.144925,0.094709,0.299255,0.063,0.786,0.085,0.040,0
2,86,0.170362,0.236801,0.094162,0.191645,0.151905,0.155126,0.031,0.786,0.075,0.074,0
3,92,0.345439,0.123362,0.046313,0.099311,0.069136,0.316438,0.022,0.666,0.112,0.195,1
4,86,0.069721,0.170406,0.014859,0.124758,0.550456,0.069800,0.034,0.773,0.156,0.005,0
...,...,...,...,...,...,...,...,...,...,...,...,...
146,86,0.249565,0.163183,0.108720,0.126531,0.019208,0.332792,0.047,0.246,0.129,0.570,0
147,86,0.144463,0.281143,0.025940,0.096741,0.079203,0.372510,0.062,0.704,0.080,0.135,1
148,74,0.129132,0.276883,0.083767,0.167773,0.182157,0.160287,0.082,0.502,0.246,0.102,0
149,86,0.074678,0.324675,0.201479,0.149183,0.106143,0.143841,0.145,0.283,0.322,0.066,0
150,0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000,0.000,0.000,0.000,0

In [48]:
x_testing.to_csv('logreg.csv')

In [49]:
testing

,ID,score_tag,agreement,subjectivity,confidence,irony,happy,angry,bored,fear,sad,excited,spam,news,feedback,marketing,Class
0,1,N,DISAGREEMENT,SUBJECTIVE,86,NONIRONIC,0.141304,0.263039,0.030370,0.162778,0.102869,0.299641,0.018,0.615,0.034,0.330,?
1,2,NEU,DISAGREEMENT,SUBJECTIVE,83,NONIRONIC,0.160947,0.264761,0.035402,0.144925,0.094709,0.299255,0.063,0.786,0.085,0.040,?
2,3,P,DISAGREEMENT,OBJECTIVE,86,NONIRONIC,0.170362,0.236801,0.094162,0.191645,0.151905,0.155126,0.031,0.786,0.075,0.074,?
3,4,P,AGREEMENT,SUBJECTIVE,92,NONIRONIC,0.345439,0.123362,0.046313,0.099311,0.069136,0.316438,0.022,0.666,0.112,0.195,?
4,5,N,DISAGREEMENT,SUBJECTIVE,86,NONIRONIC,0.069721,0.170406,0.014859,0.124758,0.550456,0.069800,0.034,0.773,0.156,0.005,?
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,146,NEU,DISAGREEMENT,SUBJECTIVE,83,NONIRONIC,0.269992,0.125215,0.000000,0.195419,0.160119,0.249255,0.156,0.448,0.251,0.121,?
146,147,NEU,DISAGREEMENT,SUBJECTIVE,86,NONIRONIC,0.249565,0.163183,0.108720,0.126531,0.019208,0.332792,0.047,0.246,0.129,0.570,?
147,148,N,DISAGREEMENT,SUBJECTIVE,86,NONIRONIC,0.144463,0.281143,0.025940,0.096741,0.079203,0.372510,0.062,0.704,0.080,0.135,?
148,149,N,DISAGREEMENT,SUBJECTIVE,74,IRONIC,0.129132,0.276883,0.083767,0.167773,0.182157,0.160287,0.082,0.502,0.246,0.102,?
149,150,N,DISAGREEMENT,SUBJECTIVE,86,NONIRONIC,0.074678,0.324675,0.201479,0.149183,0.106143,0.143841,0.145,0.283,0.322,0.066,?

In [50]:
len(feature_cols)

11